import { StyleSheet } from "react-native";
import Size from "../../assets/Size";


const style = StyleSheet.create({
  Gestur: {
    height: "100%",
    position: "absolute",
    width: "100%",
  },
  viewGestur: {
    flex: 1, padding: 24, backgroundColor: "rgba(52, 52, 52, 0.8)",
  },
  SvgX: {
    marginTop: Size.size23,
    justifyContent: "flex-end",
    flexDirection: "row",
    marginRight: Size.size23,
  },
  titleView: {
    alignItems: "center",
    marginTop: -22,
  },
  textTitle: {
    fontFamily: "Montserrat",
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: Size.size16,
    lineHeight: Size.size24,
    letterSpacing: 0.25,
    color: "#11493E",
  },
  viewName: {
    flexDirection: "row",
    marginTop:Size.size24,
    marginLeft:Size.size23
  },
  Employee: {
    fontFamily: "Montserrat",
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: Size.size14,
    lineHeight: Size.size16,
    letterSpacing: 0.25,
    color: "#616062",
  },
  Surname:{
    fontFamily: "Montserrat",
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: Size.size14,
    lineHeight: Size.size16,
    letterSpacing: 0.25,
    color: "#347474",
    marginLeft:Size.size12
  },
  date:{
    fontFamily: "Montserrat",
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: Size.size14,
    lineHeight: Size.size16,
    letterSpacing: 0.25,
    color: "#347474",
    marginLeft:Size.size51
  },
  viewDate:{
    flexDirection: "row",
    marginTop:Size.size18,
    marginLeft:Size.size23
  },
  viewComment:{
    marginTop:Size.size18,
    marginLeft:Size.size23
  },
  comment:{
    marginTop:Size.size12,
    width:Size.size287,
    height:Size.size64,
  },
  textComment:{
    fontFamily: "Montserrat",
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: Size.size14,
    lineHeight: Size.size16,
    letterSpacing: 0.25,
    color: "#949494",
  },
  ViewHourly:{
    marginLeft: Size.size25,
    marginTop: Size.size30
  },
  TextHourly:{
    fontFamily: "Montserrat",
    fontStyle: "normal",
    fontWeight: "500",
    fontSize: Size.size16,
    lineHeight: Size.size24,
    letterSpacing: 0.25,
    color: "#11493E",
  },
  TextDate:{
    fontFamily: "Montserrat",
    fontStyle: "normal",
    fontWeight: "500",
    fontSize: Size.size16,
    lineHeight: Size.size24,
    letterSpacing: 0.25,
    color: "#11493E",
    marginTop: Size.size23,
  },
  TouchSvgCalendar:{
    backgroundColor: "#347474",
    width: Size.size289,
    height: Size.size38,
    borderRadius: Size.size4,
    justifyContent: "space-between",
    flexDirection: "row",
    alignItems: "center",
  },
  TextTime:{
    fontFamily: "Montserrat",
    fontStyle: "normal",
    fontWeight: "500",
    fontSize: Size.size16,
    lineHeight: Size.size24,
    letterSpacing: 0.25,
    color: "#FCFCFC",
  },
  TouchDuration:{
    width: Size.size108,
    height: Size.size32,
    borderWidth: Size.size1,
    borderStyle: "solid",
    borderColor: "#347474",
    borderRadius: Size.size4,
    justifyContent: "center",
    alignItems: "center",
  },
  TextDuration:{
    fontFamily: "Montserrat",
    fontStyle: "normal",
    fontWeight: "500",
    fontSize: Size.size14,
    lineHeight: Size.size16,
    letterSpacing: 0.25,
    color: "#949494",
  },
  area:{
    width: Size.size315,
    borderWidth:Size.size1,
    borderRadius:Size.size6,
    borderStyle:'solid',
    borderColor:'#E3E3E3',
    margin:Size.size12,
    marginTop:Size.size26,
    textAlignVertical: 'top',
  },
  TouchBook:{
    width: Size.size289,
    height: Size.size38,
    backgroundColor: "#11493E",
    borderRadius: Size.size4,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: Size.size20,
    marginRight: Size.size23,
  },
  TextBook:{
    fontFamily: "Montserrat",
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: Size.size14,
    lineHeight: Size.size16,
    letterSpacing: 0.25,
    color: "#FCFCFC",
  },
  TextCoose:{
    fontFamily: "Montserrat",
    fontStyle: "normal",
    fontWeight: "500",
    fontSize: Size.size16,
    lineHeight: Size.size24,
    letterSpacing: 0.25,
    color: "#11493E",
  },
  TouchSelect:{
    width: Size.size335,
    height: Size.size38,
    backgroundColor: "#11493E",
    borderRadius: Size.size4,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: Size.size20,
    marginRight: Size.size23,
    marginTop: Size.size40,
  },
  TextSelect:{
    fontFamily: "Montserrat",
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: Size.size14,
    lineHeight: Size.size16,
    letterSpacing: 0.25,
    color: "#FCFCFC",
  },
  TextGreate:{
    fontFamily: 'Montserrat',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: Size.size16,
    lineHeight: Size.size24,
    letterSpacing: 0.25,
    color: '#11493E',
    marginTop:Size.size32
  },
  TextTimeGreate:{
    fontFamily: 'Montserrat',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: Size.size14,
    lineHeight: Size.size16,
    letterSpacing: 0.25,
    color: '#6B6A6C',
    marginTop:Size.size29
  },
  TextVacation:{
    fontFamily: "Montserrat",
    fontStyle: "normal",
    fontWeight: "500",
    fontSize: Size.size16,
    lineHeight: Size.size24,
    letterSpacing: 0.25,
    color: "#11493E",
  },
  TextMounthYear:{
    fontFamily: "Montserrat",
    fontStyle: "normal",
    fontWeight: "500",
    fontSize: Size.size16,
    lineHeight: Size.size24,
    letterSpacing: 0.25,
    color: "#11493E",
    marginTop: Size.size10,
  },
  CalendarView:{
    width: Size.size400,
    alignItems: "center",
    height: Size.size252
  },
  TouchBookVacation:{
    width: Size.size335,
    height: Size.size38,
    backgroundColor: "#11493E",
    borderRadius: Size.size4,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: Size.size20,
    marginRight: Size.size23,
  }
});
export default style;
