import { StyleSheet } from "react-native";
import Size from "../../assets/Size";


const style = StyleSheet.create({
  body: {
    backgroundColor: "#F5F5F5",
    width: "100%",
    height: "100%",
    maxWidth: Size.size340,
    marginLeft: Size.size18,
    marginRight: Size.size21,
    position: "relative",
  },
  titleView: {
    marginTop: Size.size30,
    alignItems: "center",
  },
  titleText: {
    fontFamily: "Montserrat",
    fontStyle: "normal",
    fontWeight: "500",
    fontSize: Size.size16,
    lineHeight: Size.size24,
    letterSpacing: 0.25,
    color: "#1B3131",
  },
  TouchView: {
    marginTop: Size.size30,
    marginLeft: Size.size30,
  },
  line: {
    width: Size.size310,
    height: Size.size1,
    backgroundColor: "#E3E3E3",
    marginTop: Size.size8,
    marginLeft: Size.size15 * -1,
  },
  Touches: {
    marginTop: Size.size12,
  },
  taskesView: {
    width: Size.size315,
    height: Size.size55,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    backgroundColor: "#EDF3F4",
    marginTop: Size.size10,
  },
  ViewTitle: {
    marginRight: Size.size80,
  },
  createTask: {
    fontFamily: "Montserrat",
    fontStyle: "normal",
    fontWeight: "500",
    fontSize: Size.size16,
    lineHeight: Size.size24,
    letterSpacing: 0.25,
    color: "#616062",
  },
  createTaskDate: {
    fontFamily: "Montserrat",
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: Size.size12,
    lineHeight: Size.size16,
    letterSpacing: 0.25,
    color: "#949494",
  },
  viewProject: {
    width: Size.size56,
    height: Size.size16,
    backgroundColor: "#38A98E",
    justifyContent: "center",
    alignItems: "center",
  },
  textProject: {
    fontFamily: "Montserrat",
    fontStyle: "normal",
    fontWeight: "300",
    fontSize: Size.size11,
    lineHeight: Size.size16,
    letterSpacing: 0.25,
    color: "#FCFCFC",
  },
  textVictory: {
    marginLeft: Size.size6,
    fontFamily: "Lato",
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: Size.size12,
    lineHeight: Size.size14,
    letterSpacing: 0.5,
    color: "#2D2D2D",
  },
  input: {
    width: Size.size315,
    height: Size.size45,
    borderWidth: Size.size1,
    borderStyle: "solid",
    borderColor: "#D1CDCD",
    borderRadius: Size.size4,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  textSearch: {
    marginLeft: Size.size18,
    fontFamily: "Montserrat",
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: Size.size12,
    lineHeight: Size.size16,
    letterSpacing: 0.25,
    color: "#DEDEDE",
  },
  textSearchActive: {
    marginLeft: Size.size18,
    fontFamily: "Montserrat",
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: Size.size12,
    lineHeight: Size.size16,
    letterSpacing: 0.25,
    color: "black",
  },
  eventView: {
    width: Size.size315,
    height: Size.size111,
    backgroundColor: "#FFFFFF",
    marginTop: Size.size15,
    borderRadius: Size.size6,
    flexDirection: "row",
  },
  titleEvenet: {
    fontFamily: "Montserrat",
    fontStyle: "normal",
    fontWeight: "500",
    fontSize: Size.size16,
    lineHeight: Size.size24,
    letterSpacing: 0.25,
    color: "#616062",
  },
  descEvent: {
    fontFamily: "Montserrat",
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: Size.size12,
    lineHeight: Size.size14,
    letterSpacing: 0.25,
    color: "#616062",
  },
  createDateEvent: {
    fontFamily: "Montserrat",
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: Size.size12,
    lineHeight: Size.size16,
    letterSpacing: 0.25,
    color: "#949494",
  },
  eventNameTitleText: {
    fontFamily: "Montserrat",
    fontStyle: "normal",
    fontWeight: "500",
    fontSize: Size.size16,
    lineHeight: Size.size24,
    letterSpacing: 0.25,
    color: "#1B3131",
  },
  eventNameTitleView: {
    alignItems: "center",
    marginTop: Size.size30,
  },
  SvgView: {
    width: Size.size23,
    height: Size.size23,
    backgroundColor: "#E9F1F1",
    borderRadius: Size.size4,
    alignItems: "center",
    justifyContent: "center",
  },
  ViewSvgText: {
    flexDirection: "row",
    alignItems: "center",
    marginLeft: Size.size35,
    marginTop: Size.size14,
  },
  TextSvg: {
    fontFamily: "Montserrat",
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: Size.size14,
    lineHeight: Size.size16,
    letterSpacing: 0.25,
    color: "#616062",
    marginLeft: Size.size8,
  },
  textDescription: {
    fontFamily: "Montserrat",
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: Size.size14,
    lineHeight: Size.size16,
    letterSpacing: 0.25,
    color: "#616062",
  },
  description: {
    fontFamily: "Montserrat",
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: Size.size14,
    lineHeight: Size.size16,
    letterSpacing: 0.25,
    color: "#949494",
    marginTop: Size.size4,
  },
  SurnameText: {
    fontFamily: "Montserrat",
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: Size.size14,
    lineHeight: Size.size16,
    letterSpacing: 0.25,
    color: "#616062",
  },
  Category: {
    fontFamily: "Montserrat",
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: Size.size12,
    lineHeight: Size.size16,
    letterSpacing: 0.25,
    color: "#616062",
  },
  toucheProject: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    marginTop: Size.size30,
  },
  ProjectNameText: {
    fontFamily: "Montserrat",
    fontStyle: "normal",
    fontWeight: "500",
    fontSize: Size.size16,
    lineHeight: Size.size18,
    letterSpacing: 0.25,
    color: "#616062",
  },
  ProjectDescriptionText: {
    fontFamily: "Montserrat",
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: Size.size14,
    lineHeight: Size.size16,
    letterSpacing: 0.25,
    color: "#949494",
    marginTop: Size.size3,
  },
  line2: {
    width: Size.size340,
    height: Size.size1,
    backgroundColor: "#E3E3E3",
    marginTop: Size.size15,
    marginBottom: Size.size15,
    marginLeft: Size.size22,
  },
  projectNameText: {
    fontFamily: "Montserrat",
    fontStyle: "normal",
    fontWeight: "500",
    fontSize: Size.size16,
    lineHeight: Size.size24,
    letterSpacing: 0.25,
    color: "#1B3131",
  },
  SurnameText1: {
    fontFamily: "Montserrat",
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: Size.size14,
    lineHeight: Size.size16,
    letterSpacing: 0.25,
    color: "#616062",
  },
  Category1:{
    fontFamily: "Montserrat",
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: Size.size14,
    lineHeight: Size.size16,
    letterSpacing: 0.25,
    color: "#616062",
  },
  view:{
    marginTop: Size.size30,
    marginLeft: Size.size35
  },
  ViewImg:{
    marginTop: Size.size13,
    flexDirection: "row",
    alignItems: "center"
  },
  ViewImg2:{
    marginTop: Size.size13,
    marginLeft:Size.size30,
    flexDirection: "row",
    alignItems: "center"
  }
});
export default style;
